### ISSUE TITLE
Clean up branches

### ISSUE THREAD

**Issue by haesleinhuepf** [clEsperanto/clesperantoj_prototype#11]
Hi Stephane @StRigaud ,

as just discussed: we should merge the recent changes to the main branch so that the repository can be built by others. I'm also CCing my colleague @StefanHahmann who is also curious how to build clesperantoj ;-)

Thanks!

Best,
Robert

**Comment by StRigaud** [comment]
The repo is a bit of a mess. Last branch I worked on is `test_stephane_linux`. I would say this is the one we need to continue and extend. The rest of the branches are alternative tests and/or old version that should not work anymore though some piece of code can still be salvaged.

Currently where are we?
- it build on linux and windows (both shared library)
- simili to the python wrapper, we have an intermediate C++ layer (native) 
- javacpp generate code (src/gen/...) from the C++ code
- we can use the generated classes in a java code
- all is controled via the pom.xml

Possible stuff to work on:
- portability and deployment? never did that for java, I am lost in this
- manage library link (windows require the path to OpenCL ...)
- how we could improve the java wrapper code for cleaner and simpler usage
- how to bridge with other java code (fiji, matlab, etc.)

On this branch for now, in order to build the javawrapper, you need:
- java JDK 8
- maven
- cmake
- shell
- git

All in PATH. Then running the `mvn` cmd should do the trick with, as always, maybe a need to delete the stuff in between the `<excecution> ... </excecution>` and then run it again with the code.

Hope this help!

**Comment by StRigaud** [comment]
- #13 

I let you guys look at the other branch if you want to keep some code left there for "recycling" and I will delete the rest for a fresh start

**Comment by StRigaud** [comment]
Repo is up to date with a main that should now build on most local machine (osx, win, unix)

All new branches are now focusing on improving the stability of the build and developping the library functionality
