### ISSUE TITLE
make a workflow for auto deployement to maven.scijava

### ISSUE THREAD

**Issue by StRigaud** [clEsperanto/clesperantoj_prototype#56]
when we define a release tag

**Comment by tpietzsch** [comment]
For "normal" pure java projects there is already automation for this in https://github.com/scijava/scijava-scripts

In particular,
* the `github-actionify.sh` script sets up GitHub Actions for deploying release-tagged versions to maven.scijava, sets up required Secrets etc...
* the `release-version.sh` script creates and pushes a release tag after verifying that tests run etc.

For clesperantoj it is more problematic because we need to build and package binaries for all platforms.
@carlosuc3m @tinevez are you aware of any scijava-related project where we already do something like this?

**Comment by tpietzsch** [comment]
maybe somebody on zulip knows... https://imagesc.zulipchat.com/#narrow/stream/327237-SciJava/topic/release-version.20infrastructure.20with.20native.20libs knows

**Comment by carlosuc3m** [comment]
Hello @StRigaud @tpietzsch @tinevez 
I've been diving deep into this issue and I've got some thoughts to share. I'll do my best to explain my ideas as clearly as possible. Here's what I'm thinking:

* My ideas revolve around using the awesome and already existing project [scijava-scripts](https://github.com/scijava/scijava-scripts), which I would say is the standard to deploy and release Maven Jar artifacts to the scijava maven repository. I say that it is the standard because I do not know any other way to do it 😂.

In addition the scripts are pretty robust and easy to use. They also ensure certain good practices are met such as licensing every Java file or having a detailed list of contributors. They also enforce a great version management. During development the version is always a SNAPSHOT, and it is only when a release happens that a definitive version is deployed/released.

This mechanism also releases new SNAPSHOTS after every commit or pull request to the main branch of the project.

**Understanding how it works**

To be able to explain my proposal correctly we need first to understand how the scijava-scripts and actions work.

1. Clone the [scijava-scripts](https://github.com/scijava/scijava-scripts) locally.
2. Run locally the bash file [`github-actionify.sh`](https://github.com/scijava/scijava-scripts/blob/main/github-actionify.sh). This script adds the build.yaml github action to our repo (clEsperanto/clesperantoj_prototype). An example of this action can be seen here: https://github.com/bioimage-io/JDLL/blob/main/.github/workflows/build.yml. 
Once the repo has the scijava action, a normal push to the main branch will trigger a new snapshot release and the **creation of a new tag**, which is associated with a new version release, will release a new final version.
3. I think that after the previous step or before, someone with access to the scijava repo has to add the keys and passwords to it.  We can ask the scijava people for help with this.

4. Once the scijava CI is fully set up, SNAPSHOT versions will be released with every commit or pull request to the main branch. The repository is also ready to release final versions.

5. In order to release a final version, we need to come back to our local clone of the scijava-scripts repo. We need to run the bash script [`release-version.sh`](https://github.com/scijava/scijava-scripts/blob/main/release-version.sh) with an argument. THe argument is the path to our local repository of interest (/path/to/clesperantoj_prototype). This script perform the corresponding checks and if everything is okay it triggers the creation of a new tag, which then triggers the build action to release a new final version.

The mechanism is quite robust and stable, but it cannot be applied directly to our project due to the presence of native libraries. Each native library needs to be compiled in the corresponding OS. This is not complatible with the current Scijava CI, however we could do some modifications to make it compatible.

**CI for our case**

For our case, we could either do something similar to what was already done for clij2. I have been looking at the code and the imagej update site: https://sites.imagej.net/clij2/lib/ and it seems that the native libraries are uploaded separately to the Java Jar file. And the process seems manual (sorry if I am wrong).

In my opinion it is not the best option as I think that the objective is that clesperanto can be used from maven as a standard Jar file without worrying about anything else.

This is why I think that adapting the existing Scijava CI is a great option for us.

**Adapting Scijava Ci for our case**

The key part that prevents us from directly using the scijava scripts is the need to package all the native libraries, created in independent Github runners into one Jar. I have already drafted a Github action that creates a unified Jar file in the branch [`deploy-to-scijava`](https://github.com/clEsperanto/clesperantoj_prototype/tree/deploy-to-scijava).

In order to adapt the scijava CI to our case we would only need worry about the `build.yaml` action, specifically the line executing the script [`build.sh`](https://github.com/bioimage-io/JDLL/blob/f51cf4284290eebbf55d8a3faff440bc26f6b120/.github/workflows/build.yml#L29).

If we look into the build.sh file we can find that the Jar file is released to Scijava maven in [this if block](https://github.com/scijava/scijava-scripts/blob/756eb8e79cf8f5f5aa1d429db39419e209f3ac8b/ci-build.sh#L238):

```
	# Run the build.
	if [ "$deployOK" -a -f release.properties ]; then
		echo
		echo "== Cutting and deploying release version =="
		BUILD_ARGS="$BUILD_ARGS release:perform"
	elif [ "$deployOK" ]; then
		echo
		echo "== Building and deploying main branch SNAPSHOT =="
		BUILD_ARGS="-Pdeploy-to-scijava $BUILD_ARGS deploy"
	else
		echo
		echo "== Building the artifact locally only =="
		BUILD_ARGS="$BUILD_ARGS install javadoc:javadoc"
	fi
	# Check the build result.
	{ mvn $BUILD_ARGS; echo $? > exit-code; } | tee mvn-log
	checkSuccess "$(cat exit-code)" mvn-log
```

If a new final version is being released, the script uses `mvn release:perform` and if it is just  a new snapshot, `mvn deploy` is being used.

The trick is that `mvn deploy` can be used to deploy an existing file if we to `mvn mvn deploy:deploy-file  -Dfile=/path/to/your-prebuilt-jar.jar`.

Thus we could extend the action so at the beginning it prebuilds the Jar with the three dynamic libraries, do a fork of the scijava scripts and modify this script so we can control what we deploy.

What do you think?

I will start trying to draft this, it might take less time than writing this huge text 😂😂

**Comment by carlosuc3m** [comment]
Sorry for the long text, here is a TL;DR:

Deployment of clesperantoj is difficult because it requires compiling everything in three separate packages. I think we could adapt what already exists to [release Jars to Scijava maven](https://github.com/scijava/scijava-scripts/tree/main) to our own case.

**Comment by carlosuc3m** [comment]
> maybe somebody on zulip knows... https://imagesc.zulipchat.com/#narrow/stream/327237-SciJava/topic/release-version.20infrastructure.20with.20native.20libs

Ups, just saw what @tpietzsch posted and what Curtis is replied in Zulip. I guess it is basically the same. And if it is already done, it will be easier. Have you had a look at something already?

**Comment by carlosuc3m** [comment]
Sorry it's me again! 
I have carefully read what curtis says on its message and it is even better than what I proposed. Basically add a command to the maven release to bundle the natieve libraries in the Jar at the same time as the plugin is being released!

This is definitely faster and cleaner. I will give it a try! Unless you have been able to do something @tpietzsch

**Comment by StRigaud** [comment]
This is out of my knowledge for both Java deployement and `maven-scijava`. So I let you try.

Just do not forget to maybe update the `pom.xml` (happy to help if we need to fix some info).
Possibly, before deployement, we may need to fix the Icy error, see #61

**Comment by haesleinhuepf** [comment]
Hi all,

just a note: In case this becomes complicated, we can also deploy to maven central. We can see in the clij parent pom how this works:  https://github.com/clij/clij-parent-pom/blob/master/pom.xml#L375-L383

But I'm also fine with deploying to scijava - in particular if that's easier.

**Comment by StRigaud** [comment]
reopenning because we are missing the SIGNING_ASC secret in the repo and trying to figure out how to get it for uploading to maven.scijava.

@haesleinhuepf, @tpietzsch, @tinevez any ideas to help us here? Is it a GPG kind of key I need to generate or something that Curtis should provide me?

**Comment by tinevez** [comment]
Please ask Curtis directly.

**Comment by StRigaud** [comment]
> Please ask Curtis directly.

already done but still early in his timezone :)

**Comment by StRigaud** [comment]
works now!
